### PR TITLE
Improvements to INDRA demo notebook

### PR DESCRIPTION
**Pull request by bgyori**
In this PR I made the following changes:
- Rename some functions to be better interpretable, and change some function APIs to make it cleaner
- Added a docstring to each function to explain what they do
- Modify some f-strings to make the code compatible with Python < 3.12
- Make the filter for "opposite direction" statements optional - the result looks okay even if the filter is off
- Nodes in the result graph are now gene names rather than IDs
- Added support for HTML evidence browser page generation. This can be embedded into the notebook but I commented that out since the HTML rendering makes the notebook UI a bit messed up on my end.

### CODE REVIEW

**Comment by bgyori** [comment]
One additional note: it would be best to refer to https://github.com/sorgerlab/indra.git as a dependency rather than indra==1.22.0 since I haven't made a release for a while and there are improvements to the code that would be good to use. In the meantime I can also work on a new release.

**Comment by tonywu1999** [comment]
> One additional note: it would be best to refer to https://github.com/sorgerlab/indra.git as a dependency rather than indra==1.22.0 since I haven't made a release for a while and there are improvements to the code that would be good to use. In the meantime I can also work on a new release.

That makes sense.  I updated the requirements.txt file to pull from https://github.com/sorgerlab/indra.git instead of INDRA 1.22.0 - [commit](https://github.com/tonywu1999/IndraDemo/commit/43855cc5c685855dc596816ba128941d04fd139a)

**Comment by tonywu1999** [comment]
I'm getting an error at `html_str = ha.make_model()`

```
File ~/workspace/IndraDemo/.venv/lib/python3.12/site-packages/indra/util/statement_presentation.py:283, in StmtStat.from_dicts(cls, dict_data, data_type, agg_class)
    281 for h, data_dict in dict_data.items():
    282     for name, value in data_dict.items():
--> 283         data_groups[name][h] = value
    284     data_groups = dict(data_groups)
    286 classes = []

KeyError: 'reach'
```

I updated INDRA to the version on github.  Is there anything else a user would need to do to make this portion work as expected?

**Comment by bgyori** [comment]
Can you check if the code is the latest on your end? I merged some code yesterday that streamlines the handling of source counts and that is needed here.

**Comment by tonywu1999** [comment]
>Can you check if the code is the latest on your end? I merged some code yesterday that streamlines the handling of source counts and that is needed here.

You're right.  For some reason it's not pulling the latest commit on my end.  I'll update you when I get it working.

**Comment by tonywu1999** [comment]
Got it working now.  The HTML assembler output looks really cool and useful.  Will go ahead and merge.

**Pull request merged**
